

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "CUSTOMERS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(255) NOT NULL, "EMAIL" VARCHAR(255) NOT NULL,"PASSWORD" VARCHAR(255) NOT NULL);
CREATE TABLE "EVENTS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CODE" VARCHAR(255) NOT NULL, "TITLE" VARCHAR(255) NOT NULL,"DESCRIPTION" VARCHAR(255) NOT NULL);
CREATE TABLE "REGISTRATIONS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), EVENT_ID INTEGER NOT NULL, CUSTOMER_ID INTEGER NOT NULL, REGISTRATION_DATE TIMESTAMP NOT NULL, NOTES VARCHAR(255) NOT NULL);
-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");
ALTER TABLE "EVENTS" ADD CONSTRAINT "SQL120325130144012" PRIMARY KEY ("ID");
ALTER TABLE "REGISTRATIONS" ADD CONSTRAINT "SQL120325130144013" PRIMARY KEY ("ID");

